name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build-docker:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build service
        run: docker build .

  build-windows:
    name: Build Windows executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Perl for Windows build
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.40"

      - name: Install Perl dependencies for Windows build
        run: cpan -i PAR PAR::Dist PAR::Packer

      - name: Build Windows executable
        run: pp -M sub::Util -o zap2xml.exe zap2xml.pl

      - name: Cache once for testing
        uses: actions/upload-artifact@v4
        with:
          path: zap2xml.exe
          retention-days: 1
