name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build service
        run: docker build .

  build-windows:
    name: Build Windows executable
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Perl for Windows build
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.40"

      - name: Install Perl dependencies for Windows build
        run: |
          cpanm --notest PAR::Packer
          cpanm --notest Compress::Zlib
          cpanm --notest Encode
          cpanm --notest File::Basename
          cpanm --notest File::Copy
          cpanm --notest Getopt::Std
          cpanm --notest HTTP::Cookies
          cpanm --notest URI
          cpanm --notest URI::Escape
          cpanm --notest LWP::UserAgent
          cpanm --notest LWP::ConnCache
          cpanm --notest POSIX
          cpanm --notest Time::Local
          cpanm --notest Time::Piece
          cpanm --notest JSON

      - name: Build Windows executable
        run: pp -o zap2xml.exe zap2xml.pl

      - name: Copy entrypoint.bat
        run: |
          copy entrypoint.bat dist\entrypoint.bat
          copy zap2xml.exe dist\zap2xml.exe
        shell: cmd

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap2xml-windows
          path: dist/
          retention-days: 1
