name: Release
on:
  push:
    branches:
      - main
jobs:
  build-tag-release:
    name: Build, tag, and release Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup release please
        uses: google-github-actions/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          changelog-path: CHANGELOG.md
          package-name: zap2xml
      - name: Login into GitHub Container Registry
        if: ${{ steps.release.outputs.release_created }}
        run: echo ${{ github.token }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Build Docker image
        if: ${{ steps.release.outputs.release_created }}
        run: |
          docker build \
          -t "ghcr.io/${GITHUB_REPOSITORY}:${{ steps.release.outputs.tag_name }}" \
          -t "ghcr.io/${GITHUB_REPOSITORY}:latest" .
      - name: Release Docker image
        if: ${{ steps.release.outputs.release_created }}
        run: |
          docker push "ghcr.io/${GITHUB_REPOSITORY}:${{ steps.release.outputs.tag_name }}"
          docker push "ghcr.io/${GITHUB_REPOSITORY}:latest"
